name: c-count-env

channels:
  - conda-forge
  - bioconda
  - anaconda

dependencies:
  - python=3.8
  - numpy
  - scipy
  - keras
  - tensorflow-gpu
  - scikit-learn
  - scikit-image
  - matplotlib
  - pandas
  - aicsimageio
  - jupyterlab
  - ipython
  - opencv
  - imgaug
  - snakemake
  - seaborn
  - graphviz
  - pip
  - pip:
    - aicspylibczi>=3.0.5 
