name: ccount
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - scipy
  - keras
  - tensorflow
  - scikit-learn
  - scikit-image
  - matplotlib
  - pandas
  - aicsimageio
  - jupyterlab
  - ipython
  - opencv
  - imgaug
  - snakemake
  - aicspylibczi>=3.0.5 # added by kai
  - seaborn # added by kai
